# Generated by Django 4.1.6 on 2023-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
