# Generated by Django 4.1.6 on 2023-02-11 15:09

from django.db import migrations
import notes.manager


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', notes.manager.CustomUserManager()),
            ],
        ),
    ]
